'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const test = require('node:test');
const {
  applyBlastRadiusResults,
  exportChangeReviewEvidence,
  planBlastRadius,
  renderBlastRadius,
  validateChangeReview
} = require('../skills/godaudits/runtime/lib/blast-radius');

const changeReviewFixture = path.join(__dirname, 'fixtures', 'change-review', 'CHANGE-REVIEW.json');

function git(repo, args) {
  return execFileSync('git', args, { cwd: repo, encoding: 'utf8' }).trim();
}

function write(repo, relative, value) {
  const target = path.join(repo, relative);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, value);
}

function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'godaudits-blast-radius-'));
  const repo = path.join(root, 'repo');
  fs.mkdirSync(repo);
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  git(repo, ['init', '-q']);
  git(repo, ['config', 'user.name', 'Test User']);
  git(repo, ['config', 'user.email', 'test@example.com']);

  write(repo, 'package.json', '{"dependencies":{"tiny-cache":"1.0.0"}}\n');
  write(repo, 'src/cache.js', "function cacheKey(tenant, id) { return `${tenant}:${id}`; }\nmodule.exports = { cacheKey };\n");
  write(repo, 'src/consumer.js', "const { cacheKey } = require('./cache');\nmodule.exports = (id) => cacheKey('tenant-a', id);\n");
  write(repo, 'api/openapi.json', '{"openapi":"3.1.0","paths":{"/items":{}}}\n');
  write(repo, 'worker.py', 'def consume_item(value):\n    return value\n');
  git(repo, ['add', '.']);
  git(repo, ['commit', '-qm', 'base']);
  const base = git(repo, ['rev-parse', 'HEAD']);

  write(repo, 'package.json', '{"dependencies":{"tiny-cache":"1.1.0"}}\n');
  write(repo, 'src/cache.js', "function cacheKey(id) { return id; }\nmodule.exports = { cacheKey };\n");
  write(repo, 'api/openapi.json', '{"openapi":"3.1.0","paths":{"/items":{"get":{"responses":{}}}}}\n');
  write(repo, 'migrations/002_add_item_state.sql', 'ALTER TABLE items ADD COLUMN state text;\n');
  write(repo, 'config/feature-flags.json', '{"new_items":true}\n');
  write(repo, 'src/codec.js', 'module.exports = (value) => JSON.stringify(value);\n');
  write(repo, 'src/lifecycle.js', 'module.exports = () => setTimeout(() => {}, 0);\n');
  write(repo, 'generated/client.generated.js', '// generated by api-codegen\nmodule.exports = {};\n');
  git(repo, ['add', '.']);
  git(repo, ['commit', '-qm', 'change']);
  const head = git(repo, ['rev-parse', 'HEAD']);
  return { repo, base, head };
}

function sourceProof(repo, relative, level = 2) {
  const value = fs.readFileSync(path.join(repo, relative), 'utf8');
  return {
    level,
    kind: level === 3 ? 'failure-path' : 'citation',
    path: relative,
    line: 1,
    quote: value.trim(),
    sha256: crypto.createHash('sha256').update(value).digest('hex'),
    ...(level === 3 ? { steps: ['Call enters cacheKey.', 'The tenant guard rejects a mismatched tenant.'] } : {})
  };
}

function executableProof(command, result = 'passed') {
  return {
    level: 4,
    kind: 'executable',
    tool: 'node:test',
    tool_version: process.versions.node,
    command,
    result,
    environment: 'disposable local fixture',
    isolation: 'outbound network disabled and no production credentials'
  };
}

function resultsFor(review, values = {}) {
  return {
    schema_version: '1.0',
    review: {
      base: review.review.base,
      head: review.review.head,
      diff_sha256: review.review.diff_sha256
    },
    ...values
  };
}

test('the shipped change-review fixture satisfies semantic validation', () => {
  const review = JSON.parse(fs.readFileSync(changeReviewFixture, 'utf8'));
  assert.deepEqual(validateChangeReview(review), []);
});

test('planBlastRadius inventories changed behavior beyond direct callers', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: [
      'Cache keys remain tenant-scoped after the cache helper signature changes.',
      'The item API remains backward-compatible for existing consumers.'
    ],
    verify: 'node --test test/cache-contract.test.js'
  });

  assert.deepEqual(validateChangeReview(review), []);
  assert.equal(review.schema_version, '1.0');
  assert.equal(review.review.base, base);
  assert.equal(review.review.head, head);
  assert.equal(review.safety_facts.length, 2);
  assert.equal(review.merge_gate.status, 'unproven');
  assert.ok(review.change.files.some((item) => item.path === 'migrations/002_add_item_state.sql'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'public-contract'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'database-schema'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'dependency-version'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'configuration-flag'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'serialization-wire'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'cross-language'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'async-lifecycle'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'cache-invalidation'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'generated-artifact'));
  assert.ok(review.impact_leads.some((lead) => lead.kind === 'public-entry-point'));
  const references = review.impact_leads.filter((lead) => lead.kind === 'direct-reference');
  assert.ok(references.some((lead) => lead.downstream_paths.includes('src/consumer.js')));
  assert.ok(review.affected_checks.includes('A-ARCH-23'));
  assert.ok(review.affected_checks.includes('A-DB-16'));
  assert.ok(review.affected_domains.includes('architecture'));
});

test('applyBlastRadiusResults records proof, real risks, cleared risks, and a passing merge gate', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: [
      'Cache keys remain tenant-scoped after the cache helper signature changes.',
      'The item API remains backward-compatible for existing consumers.'
    ],
    verify: 'node --test test/cache-contract.test.js'
  });
  const results = resultsFor(review, {
    authorization: {
      capability: 'sandbox',
      authorized_by: 'repository owner',
      environment: 'disposable local fixture',
      isolation: 'outbound network disabled and no production credentials'
    },
    safety_facts: [
      { fact: 'SF-1', outcome: 'proven', proof: executableProof('node --test test/cache-key.test.js') },
      { fact: 'SF-2', outcome: 'proven', proof: executableProof('node --test test/api-contract.test.js') }
    ],
    risks: [{
      title: 'Legacy cache entries can miss after deployment',
      mechanism: 'Old and new processes compute different cache keys during a rolling deployment.',
      likelihood: 'unlikely',
      consequence: 'Low',
      verify: 'node --test test/cache-rollout.test.js',
      proof: sourceProof(repo, 'src/cache.js')
    }],
    cleared: [{
      title: 'The API response shape remains readable by old clients',
      rationale: 'The response schema only gains optional metadata.',
      invalidated_by: 'Making the metadata field required or removing an existing response field.',
      proof: sourceProof(repo, 'api/openapi.json', 3)
    }],
    before_merge: {
      outcome: 'passed',
      proof: executableProof('node --test test/cache-contract.test.js')
    }
  });

  const applied = applyBlastRadiusResults(review, results);
  assert.deepEqual(applied.errors, []);
  assert.equal(applied.review.merge_gate.status, 'pass');
  assert.equal(applied.review.safety_facts[0].proof_level, 4);
  assert.equal(applied.review.safety_facts[0].status, 'proven');
  assert.equal(applied.review.risks[0].likelihood, 'unlikely');
  assert.equal(applied.review.cleared[0].proof_level, 3);
  assert.equal(applied.review.before_merge.status, 'passed');
  assert.ok(applied.review.review.capabilities.includes('sandbox'));
  const evidence = exportChangeReviewEvidence(applied.review, { start: 40, source: 'CHANGE-REVIEW.json' });
  assert.equal(evidence.evidence[0].id, 'E-40');
  assert.ok(evidence.evidence.some((item) => item.type === 'source'));
  assert.ok(evidence.evidence.some((item) => item.type === 'runtime'));
  assert.equal(evidence.findings_created, 0);
  assert.match(renderBlastRadius(applied.review), /Merge disposition: PASS/);
  assert.match(renderBlastRadius(applied.review), /Cleared risks/);
});

test('proof below executable level stays explicitly unproven at the merge gate', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof: sourceProof(repo, 'src/cache.js', 3) }]
  }));
  assert.deepEqual(applied.errors, []);
  assert.equal(applied.review.safety_facts[0].proof_level, 3);
  assert.equal(applied.review.merge_gate.status, 'unproven');
  assert.ok(applied.review.merge_gate.reasons.some((reason) => /level 4/.test(reason)));
});

test('executable proof requires recorded execution authority', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof: executableProof('node --test test/cache-key.test.js') }]
  }));
  assert.ok(applied.errors.some((error) => /authorization/.test(error)));
});

test('proof results are bound to the reviewed base, head, and patch hash', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const results = resultsFor(review, {
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof: sourceProof(repo, 'src/cache.js') }]
  });
  results.review.head = 'f'.repeat(40);
  const applied = applyBlastRadiusResults(review, results);
  assert.ok(applied.errors.some((error) => /results\.review\.head/.test(error)));
  assert.equal(applied.review.proofs.length, 0);
});

test('semantic validation rejects a hand-authored pass that launders lower-level proof', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof: sourceProof(repo, 'src/cache.js', 3) }]
  }));
  assert.deepEqual(applied.errors, []);
  const forged = applied.review;
  forged.safety_facts[0].proof_level = 4;
  forged.safety_facts[0].proof_kind = 'executable';
  forged.safety_facts[0].stopped_because = null;
  forged.before_merge.status = 'passed';
  forged.before_merge.proof_ids = [...forged.safety_facts[0].proof_ids];
  forged.merge_gate = { status: 'pass', reasons: [] };
  const errors = validateChangeReview(forged);
  assert.ok(errors.some((error) => /must match its current proof/.test(error)));
  assert.ok(errors.some((error) => /before_merge passed requires level 4 or 5 proof/.test(error)));
  assert.ok(errors.some((error) => /merge_gate/.test(error)));
});

test('executable proof environment matches the recorded authorization', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const results = resultsFor(review, {
    authorization: {
      capability: 'sandbox',
      authorized_by: 'repository owner',
      environment: 'disposable local fixture',
      isolation: 'outbound network disabled and no production credentials'
    },
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof: executableProof('node --test test/cache-key.test.js') }]
  });
  results.safety_facts[0].proof.environment = 'another checkout';
  const applied = applyBlastRadiusResults(review, results);
  assert.ok(applied.errors.some((error) => /must match the results authorization/.test(error)));
});

test('an open high-consequence risk blocks a fully proven change', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const proof = executableProof('node --test test/cache-key.test.js');
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    authorization: {
      capability: 'sandbox',
      authorized_by: 'repository owner',
      environment: 'disposable local fixture',
      isolation: 'outbound network disabled and no production credentials'
    },
    safety_facts: [{ fact: 'SF-1', outcome: 'proven', proof }],
    risks: [{
      title: 'Tenant cache entries collide',
      mechanism: 'The new key omits the tenant identifier.',
      likelihood: 'likely',
      consequence: 'High',
      verify: 'node --test test/cache-key.test.js',
      proof: sourceProof(repo, 'src/cache.js')
    }],
    before_merge: { outcome: 'passed', proof: executableProof('node --test test/cache-contract.test.js') }
  }));
  assert.deepEqual(applied.errors, []);
  assert.equal(applied.review.merge_gate.status, 'blocked');
  assert.ok(applied.review.merge_gate.reasons.some((reason) => /High/.test(reason)));
});

test('before-merge proof must run the command selected during planning', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js'
  });
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    authorization: {
      capability: 'sandbox',
      authorized_by: 'repository owner',
      environment: 'disposable local fixture',
      isolation: 'outbound network disabled and no production credentials'
    },
    before_merge: {
      outcome: 'passed',
      proof: executableProof('node --test test/different.test.js')
    }
  }));
  assert.ok(applied.errors.some((error) => /exactly match/.test(error)));
});

test('planning and applying proof never execute recorded commands and redact credentials', (t) => {
  const { repo, base, head } = fixture(t);
  const marker = path.join(repo, 'must-not-exist');
  const fakeToken = ['ghp', 'abcdefghijklmnopqrstuvwxyz123456'].join('_');
  const command = `${process.execPath} -e "require('fs').writeFileSync('${marker}','ran')" token=${fakeToken}`;
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: command
  });
  assert.equal(fs.existsSync(marker), false);
  assert.equal(JSON.stringify(review).includes(fakeToken), false);
  const applied = applyBlastRadiusResults(review, resultsFor(review, {
    authorization: {
      capability: 'sandbox',
      authorized_by: 'repository owner',
      environment: 'disposable local fixture',
      isolation: 'outbound network disabled and no production credentials'
    },
    before_merge: {
      outcome: 'passed',
      proof: executableProof(review.before_merge.command, `passed with token ${fakeToken}`)
    }
  }));
  assert.equal(fs.existsSync(marker), false);
  assert.equal(JSON.stringify(applied.review).includes(fakeToken), false);
});

test('planning joins open audit findings whose source evidence changed', (t) => {
  const { repo, base, head } = fixture(t);
  const review = planBlastRadius(repo, {
    base,
    head,
    facts: ['Cache keys remain tenant-scoped after the cache helper signature changes.'],
    verify: 'node --test test/cache-contract.test.js',
    audit: {
      evidence: [{ id: 'E-1', type: 'source', path: 'src/cache.js' }],
      findings: [{
        id: 'F-ARCH-9', domain: 'architecture', status: 'open',
        evidence: ['E-1'], checks: ['A-ARCH-24']
      }]
    }
  });
  const auditLead = review.impact_leads.find((lead) => lead.kind === 'audit-finding');
  assert.deepEqual(auditLead.finding_ids, ['F-ARCH-9']);
  assert.ok(review.affected_checks.includes('A-ARCH-24'));
});
