#!/usr/bin/env bash
# Generate the compact and full portable prompts.
#
# PROMPT.md contains the orchestrator plus the four core contracts. It is for
# focused audits on constrained chat surfaces and declares reduced coverage.
# PROMPT.full.md contains every domain module and the report template. It is
# the standalone full-audit prompt for clients with a large context window.
#
# Usage:
#   bash scripts/build-prompt.sh
#   bash scripts/build-prompt.sh --check

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL="$REPO_DIR/skills/godaudits/SKILL.md"
REFS="$REPO_DIR/skills/godaudits/references"
TEMPLATE="$REPO_DIR/skills/godaudits/templates/AUDIT.template.mdx"
COMPACT="$REPO_DIR/PROMPT.md"
FULL="$REPO_DIR/PROMPT.full.md"
MODE="${1:-write}"

if [ "$MODE" != "write" ] && [ "$MODE" != "--check" ]; then
  echo "Unknown option: $MODE" >&2
  exit 1
fi

strip_frontmatter() {
  awk 'BEGIN{fm=0} /^---$/{fm++; next} fm!=1{print}' "$1"
}

strip_file_map() {
  awk 'BEGIN{skip=0} /^## File map/{skip=1; next} skip && /^## /{skip=0} !skip{print}'
}

write_header() {
  kind=$1
  cat <<EOF
# godaudits ($kind portable prompt)

You are operating under godaudits 2.1: an evidence-first audit system with a
deterministic check catalog, explicit per-check outcomes, validated JSON state,
computed scores, and a rendered MDX remediation report. The machine source of
truth is .godaudits/AUDIT.json. AUDIT.mdx is generated from it.

Generated by scripts/build-prompt.sh. Do not edit by hand.

---
EOF
}

generate_compact() {
  write_header "compact"
  cat <<'EOF'

Coverage notice: this compact prompt inlines the orchestrator and core
contracts, but not the 18 domain modules. Use it only for focused audits where
the requested module is separately available. If a module is unavailable,
mark its checks unknown and report reduced coverage. Never approximate a full
audit from memory. Use PROMPT.full.md for the complete 424-check pack.

EOF
  strip_frontmatter "$SKILL" | strip_file_map
  for ref in audit-format intake compliance exemplar; do
    printf '\n\n---\n\n# INLINED REFERENCE: references/%s.md\n\n' "$ref"
    cat "$REFS/$ref.md"
  done
}

generate_full() {
  write_header "full"
  cat <<'EOF'

Coverage notice: this file includes all 18 domain modules and the complete
report contract. Evaluate every applicable check. A check not inspected is
unknown, never pass. Run the deterministic CLI validation before presenting.

EOF
  strip_frontmatter "$SKILL" | strip_file_map
  for ref in audit-format intake compliance exemplar product architecture stack database security llm ux ui seo code-quality style-genome agent-memory repo build roadmap deploy observe launch; do
    printf '\n\n---\n\n# INLINED REFERENCE: references/%s.md\n\n' "$ref"
    cat "$REFS/$ref.md"
  done
  printf '\n\n---\n\n# INLINED TEMPLATE: templates/AUDIT.template.mdx\n\n'
  cat "$TEMPLATE"
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
generate_compact > "$tmp/PROMPT.md"
generate_full > "$tmp/PROMPT.full.md"

if [ "$MODE" = "--check" ]; then
  failed=0
  cmp -s "$tmp/PROMPT.md" "$COMPACT" || { echo "PROMPT.md is stale" >&2; failed=1; }
  cmp -s "$tmp/PROMPT.full.md" "$FULL" || { echo "PROMPT.full.md is stale" >&2; failed=1; }
  [ "$failed" = "0" ] && echo "Portable prompts are fresh."
  exit "$failed"
fi

mv "$tmp/PROMPT.md" "$COMPACT"
mv "$tmp/PROMPT.full.md" "$FULL"
echo "Wrote $COMPACT ($(wc -l < "$COMPACT" | tr -d ' ') lines)"
echo "Wrote $FULL ($(wc -l < "$FULL" | tr -d ' ') lines)"
